const {generateNextId}=require('./numberingEngine');

const debitMap={
 EXPENSE:'OPERATING_EXPENSE',BILL_PAYMENT:'OPERATING_EXPENSE',PAYROLL:'PAYROLL_EXPENSE',PURCHASE_ORDER_PAYMENT:'INVENTORY',
 CUSTOMER_REFUND:'CUSTOMER_RECEIVABLE',PAYMENT_REVERSAL:'TRANSFER_CLEARING',INVOICE_CANCELLATION:'CUSTOMER_RECEIVABLE',TRANSFER:'TRANSFER_CLEARING'
};
const classificationMap={OPERATING_EXPENSE:'OPERATING_EXPENSE',PAYROLL_EXPENSE:'PAYROLL_EXPENSE',MAINTENANCE_EXPENSE:'MAINTENANCE_EXPENSE',TRAVEL_ALLOWANCE:'TRAVEL_ALLOWANCE',CAPITAL_EXPENDITURE:'CAPITAL_EXPENDITURE',TAX_PAYMENT:'TAX_EXPENSE',INVENTORY_PURCHASE:'INVENTORY'};

async function systemAccount(client,companyId,key){const row=(await client.query(`SELECT id FROM chart_of_accounts WHERE company_id=$1 AND system_key=$2 AND active=true`,[companyId,key])).rows[0];if(!row)throw Object.assign(new Error(`General ledger account ${key} is not configured`),{statusCode:409});return row.id;}
async function cashAccount(client,accountId){let row=(await client.query(`SELECT a.company_id,a.gl_account_id,a.name,a.account_type FROM accounts a WHERE a.id=$1`,[accountId])).rows[0];if(!row)throw Object.assign(new Error('Operational account not found for journal'),{statusCode:404});if(!row.gl_account_id){const code=`10${String(accountId).replaceAll('-','').slice(0,10)}`;row.gl_account_id=(await client.query(`INSERT INTO chart_of_accounts(company_id,code,name,account_class,account_subtype,normal_balance,system_key) VALUES($1,$2,$3,'ASSET',$4,'DEBIT',$5) ON CONFLICT(company_id,system_key) DO UPDATE SET name=EXCLUDED.name RETURNING id`,[row.company_id,code,row.name,String(row.account_type).toUpperCase(),`CASH_ACCOUNT_${accountId}`])).rows[0].id;await client.query(`UPDATE accounts SET gl_account_id=$1 WHERE id=$2`,[row.gl_account_id,accountId]);}return row;}
async function postAccountMovementJournal(client,{transactionId,accountId,transactionType,amount,referenceType,referenceId,createdBy,notes,costCenterId,financialClassification}){const cash=await cashAccount(client,accountId),incoming=['DEPOSIT','TRANSFER_IN'].includes(transactionType),isTransfer=['TRANSFER_IN','TRANSFER_OUT'].includes(transactionType);let counterKey;if(isTransfer)counterKey='TRANSFER_CLEARING';else if(incoming)counterKey=referenceType==='CUSTOMER_PAYMENT'?'CUSTOMER_RECEIVABLE':referenceType==='SUPPLIER_REFUND'?'INVENTORY':referenceType==='EMPLOYEE_REFUND'?'EMPLOYEE_ADVANCE':referenceType==='PAYMENT_REVERSAL'?'TRANSFER_CLEARING':'OTHER_INCOME';else counterKey=classificationMap[financialClassification]||debitMap[referenceType]||'OPERATING_EXPENSE';const counter=await systemAccount(client,cash.company_id,counterKey),businessId=await generateNextId('GL_JOURNAL'),sourceId=String(transactionId);const journal=(await client.query(`INSERT INTO journal_entries(business_id,company_id,journal_date,description,source_type,source_id,status,created_by,posted_at) VALUES($1,$2,CURRENT_DATE,$3,'ACCOUNT_TRANSACTION',$4,'posted',$5,now()) ON CONFLICT(company_id,source_type,source_id) DO NOTHING RETURNING id`,[businessId,cash.company_id,notes||`${transactionType} ${referenceType||''}`,sourceId,createdBy||null])).rows[0];if(!journal)return null;const lines=incoming?[[cash.gl_account_id,amount,0],[counter,0,amount]]:[[counter,amount,0],[cash.gl_account_id,0,amount]];for(const [gl,debit,credit] of lines)await client.query(`INSERT INTO journal_lines(journal_entry_id,gl_account_id,debit,credit,memo,cost_center_id) VALUES($1,$2,$3,$4,$5,$6)`,[journal.id,gl,debit,credit,notes||referenceId||null,costCenterId||null]);return journal.id;}
module.exports={postAccountMovementJournal};
