-- Green Gold ERP - Phase 1 core schema
-- Design notes:
--   * Every business-facing entity has a permanent, human-readable business_id
--     (generated by the numbering engine) plus a hidden UUID technical id.
--     Business IDs are never reused, even if the row is soft-deleted.
--   * Master records (customer/vendor/employee) are separate from login
--     accounts (users). A login account links to a master record only after
--     an explicit approval step (link_requests table).
--   * All destructive actions should go through soft delete (deleted_at)
--     wherever the row represents a permanent business record.

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- for gen_random_uuid()

-- ============================================================
-- Company structure
-- ============================================================

CREATE TABLE companies (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    country         TEXT NOT NULL DEFAULT 'BD',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE branches (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies(id),
    name            TEXT NOT NULL,
    address         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE departments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    branch_id       UUID NOT NULL REFERENCES branches(id),
    name            TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Modules, roles, permissions (granular per-module access)
-- ============================================================

CREATE TABLE modules (
    id              SERIAL PRIMARY KEY,
    code            TEXT NOT NULL UNIQUE,   -- e.g. DASHBOARD, INVENTORY, SALES, ACCOUNTS, HR
    name            TEXT NOT NULL
);

CREATE TABLE permissions (
    id              SERIAL PRIMARY KEY,
    module_id       INTEGER NOT NULL REFERENCES modules(id),
    code            TEXT NOT NULL UNIQUE,   -- e.g. INVENTORY_VIEW, INVENTORY_CREATE, INVENTORY_APPROVE
    name            TEXT NOT NULL
);

CREATE TABLE roles (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies(id),
    name            TEXT NOT NULL,
    description     TEXT,
    is_system_role  BOOLEAN NOT NULL DEFAULT false, -- e.g. SUPER_ADMIN, seeded, cannot be deleted
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, name)
);

CREATE TABLE role_permissions (
    role_id         UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id   INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- ============================================================
-- Master records (permanent business records)
-- ============================================================

CREATE TABLE master_employees (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id     TEXT NOT NULL UNIQUE,   -- e.g. EMP-HR-2026-000045
    company_id      UUID NOT NULL REFERENCES companies(id),
    branch_id       UUID REFERENCES branches(id),
    department_id   UUID REFERENCES departments(id),
    full_name       TEXT NOT NULL,
    designation     TEXT,
    phone           TEXT,
    email           TEXT,
    join_date       DATE,
    status          TEXT NOT NULL DEFAULT 'active', -- active, on_leave, terminated
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE master_customers (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id     TEXT NOT NULL UNIQUE,   -- e.g. CUS-BD-DHK-2026-000001
    company_id      UUID NOT NULL REFERENCES companies(id),
    name            TEXT NOT NULL,
    phone           TEXT,
    email           TEXT,
    address         TEXT,
    customer_type   TEXT,                    -- retail, wholesale, cold_storage_client, etc.
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE master_vendors (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id     TEXT NOT NULL UNIQUE,   -- e.g. VEN-BD-2026-000015
    company_id      UUID NOT NULL REFERENCES companies(id),
    name            TEXT NOT NULL,
    phone           TEXT,
    email           TEXT,
    address         TEXT,
    vendor_type     TEXT,
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

-- ============================================================
-- Login accounts (separate from master records)
-- ============================================================

CREATE TABLE users (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id          UUID NOT NULL REFERENCES companies(id),
    username            TEXT NOT NULL UNIQUE,
    email               TEXT UNIQUE,
    phone               TEXT,
    password_hash       TEXT NOT NULL,
    account_type        TEXT NOT NULL DEFAULT 'staff', -- staff, customer, vendor
    status              TEXT NOT NULL DEFAULT 'pending_approval', -- pending_approval, active, disabled
    -- If this account has been linked to a permanent master record:
    linked_employee_id  UUID REFERENCES master_employees(id),
    linked_customer_id  UUID REFERENCES master_customers(id),
    linked_vendor_id    UUID REFERENCES master_vendors(id),
    branch_id           UUID REFERENCES branches(id),
    department_id       UUID REFERENCES departments(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_by          UUID REFERENCES users(id),
    approved_at          TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    deleted_at            TIMESTAMPTZ,
    CONSTRAINT one_link_max CHECK (
        (CASE WHEN linked_employee_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN linked_customer_id IS NOT NULL THEN 1 ELSE 0 END +
         CASE WHEN linked_vendor_id  IS NOT NULL THEN 1 ELSE 0 END) <= 1
    )
);

CREATE TABLE user_roles (
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id     UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Per-user permission overrides on top of role permissions (granular
-- per-module staff access, e.g. "this user can VIEW Accounts but not
-- APPROVE", even if their role would normally allow it).
CREATE TABLE user_permission_overrides (
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_id   INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    granted         BOOLEAN NOT NULL, -- true = explicitly allow, false = explicitly deny
    PRIMARY KEY (user_id, permission_id)
);

-- New-account registration + master-record linking, both go through this
-- table so admins/HR/accounts have one place to approve access requests.
CREATE TABLE link_requests (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    requesting_user_id  UUID NOT NULL REFERENCES users(id),
    master_type         TEXT NOT NULL,  -- employee, customer, vendor
    master_business_id  TEXT NOT NULL,  -- the ID they typed in at signup
    status              TEXT NOT NULL DEFAULT 'pending', -- pending, approved, rejected
    reviewed_by         UUID REFERENCES users(id),
    reviewed_at         TIMESTAMPTZ,
    review_notes        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Numbering engine
-- ============================================================

CREATE TABLE numbering_sequences (
    id                  SERIAL PRIMARY KEY,
    module_code         TEXT NOT NULL UNIQUE,   -- e.g. CUSTOMER, EMPLOYEE, INVOICE, GATE_PASS
    prefix_template      TEXT NOT NULL,          -- e.g. 'CUS-BD-DHK-{YYYY}-' or 'INV-{YYYYMMDD}-'
    padding_length        INTEGER NOT NULL DEFAULT 6,
    current_number        BIGINT NOT NULL DEFAULT 0,
    reset_policy           TEXT NOT NULL DEFAULT 'never', -- never, yearly, monthly, daily
    last_reset_period      TEXT,                  -- tracks the period key (e.g. '2026' or '20260801') for reset logic
    format_version          INTEGER NOT NULL DEFAULT 1,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Audit log (append-only; application code must never UPDATE/DELETE rows)
-- ============================================================

CREATE TABLE audit_logs (
    id              BIGSERIAL PRIMARY KEY,
    actor_user_id   UUID REFERENCES users(id),
    action          TEXT NOT NULL,          -- e.g. USER_APPROVED, INVOICE_CREATED, GATE_PASS_SCANNED
    entity_type     TEXT NOT NULL,
    entity_id       TEXT,
    before_data     JSONB,
    after_data      JSONB,
    ip_address      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_user_id);

-- ============================================================
-- Notices / announcements (no chat system, per architecture rules)
-- ============================================================

CREATE TABLE notices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title           TEXT NOT NULL,
    body            TEXT NOT NULL,
    created_by      UUID NOT NULL REFERENCES users(id),
    target_type     TEXT NOT NULL DEFAULT 'all', -- all, branch, department, role, user, customer, vendor
    target_value    TEXT,                         -- id or code of the target, when not 'all'
    send_email      BOOLEAN NOT NULL DEFAULT false,
    send_push       BOOLEAN NOT NULL DEFAULT true,
    send_sms        BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ
);

CREATE TABLE notice_reads (
    notice_id       UUID NOT NULL REFERENCES notices(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at         TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,
    PRIMARY KEY (notice_id, user_id)
);

-- ============================================================
-- QR / barcode metadata
-- ============================================================

CREATE TABLE qr_barcode_records (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type     TEXT NOT NULL,       -- CUSTOMER, EMPLOYEE, INVOICE, GATE_PASS, etc.
    entity_id       TEXT NOT NULL,       -- the business_id being encoded
    qr_file_path    TEXT NOT NULL,
    barcode_file_path TEXT NOT NULL,
    signed_hash     TEXT NOT NULL,       -- HMAC signature embedded in the QR payload
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entity_type, entity_id)
);

-- ============================================================
-- Generic file attachments (receipts, bills, attendance/task reports, etc.)
-- ============================================================

CREATE TABLE file_attachments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type     TEXT NOT NULL,        -- EXPENSE, USER_PROFILE, TASK_REPORT, ATTENDANCE, etc.
    entity_id       TEXT NOT NULL,
    uploaded_by     UUID NOT NULL REFERENCES users(id),
    file_path       TEXT NOT NULL,
    original_name   TEXT NOT NULL,
    file_type       TEXT NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_file_attachments_entity ON file_attachments (entity_type, entity_id);
