ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;
CREATE TABLE IF NOT EXISTS password_reset_requests(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),business_id TEXT NOT NULL UNIQUE,company_id UUID NOT NULL REFERENCES companies(id),user_id UUID NOT NULL REFERENCES users(id),identifier TEXT NOT NULL,reason TEXT,status TEXT NOT NULL DEFAULT 'submitted' CHECK(status IN('submitted','approved','rejected','completed')),requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),reviewed_by UUID REFERENCES users(id),reviewed_at TIMESTAMPTZ,review_notes TEXT,completed_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_password_reset_pending ON password_reset_requests(company_id,status,requested_at DESC);
INSERT INTO numbering_sequences(module_code,prefix_template,padding_length,reset_policy) VALUES('PASSWORD_RESET','PWR-{YYYYMMDD}-',6,'daily') ON CONFLICT(module_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS integration_devices(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),business_id TEXT NOT NULL UNIQUE,company_id UUID NOT NULL REFERENCES companies(id),name TEXT NOT NULL,device_type TEXT NOT NULL,site_id UUID REFERENCES company_sites(id),department_id UUID REFERENCES departments(id),connection_id UUID REFERENCES api_connections(id),device_key TEXT NOT NULL UNIQUE,ingest_secret_hash TEXT NOT NULL,protocol TEXT NOT NULL DEFAULT 'webhook',event_type TEXT NOT NULL,field_mapping JSONB NOT NULL DEFAULT '{}',action_config JSONB NOT NULL DEFAULT '{}',threshold_config JSONB NOT NULL DEFAULT '{}',enabled BOOLEAN NOT NULL DEFAULT true,last_seen_at TIMESTAMPTZ,last_status TEXT,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS integration_device_events(id BIGSERIAL PRIMARY KEY,company_id UUID NOT NULL REFERENCES companies(id),device_id UUID NOT NULL REFERENCES integration_devices(id),external_event_id TEXT,raw_payload JSONB NOT NULL,normalized_payload JSONB NOT NULL DEFAULT '{}',event_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'received',processing_message TEXT,received_at TIMESTAMPTZ NOT NULL DEFAULT now(),processed_at TIMESTAMPTZ,UNIQUE(device_id,external_event_id));
CREATE INDEX IF NOT EXISTS idx_device_events_recent ON integration_device_events(company_id,received_at DESC);
CREATE TABLE IF NOT EXISTS integration_alerts(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),company_id UUID NOT NULL REFERENCES companies(id),device_id UUID REFERENCES integration_devices(id),event_id BIGINT REFERENCES integration_device_events(id),severity TEXT NOT NULL DEFAULT 'warning',title TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',acknowledged_by UUID REFERENCES users(id),acknowledged_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO numbering_sequences(module_code,prefix_template,padding_length,reset_policy) VALUES('INTEGRATION_DEVICE','DEV-{YYYY}-',6,'never') ON CONFLICT(module_code) DO NOTHING;
