const {query,withTransaction}=require('../config/db');
const {generateNextId}=require('../services/numberingEngine');
const {recordAccountTransaction}=require('./accountController');
const {createFinancialDocument}=require('../services/financialDocumentService');
const {generateForEntitySafe}=require('../services/qrBarcodeService');
const {logAction}=require('../services/auditLogger');

async function listCostCenters(req,res){const {rows}=await query(`SELECT cc.*,d.name department_name,b.name branch_name FROM cost_centers cc LEFT JOIN departments d ON d.id=cc.department_id LEFT JOIN branches b ON b.id=cc.branch_id WHERE cc.company_id=$1 ORDER BY cc.active DESC,cc.name`,[req.user.company_id]);res.json({costCenters:rows});}
async function createCostCenter(req,res){const {code,name,departmentId,branchId}=req.body;if(!code||!name)return res.status(400).json({error:'Code and name are required'});const businessId=await generateNextId('COST_CENTER');const {rows}=await query(`INSERT INTO cost_centers(business_id,company_id,code,name,department_id,branch_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[businessId,req.user.company_id,String(code).toUpperCase(),name,departmentId||null,branchId||null,req.user.id]);res.status(201).json({costCenter:rows[0]});}

async function requestReversal(req,res){const {transactionId,reason}=req.body;if(!transactionId||!String(reason||'').trim())return res.status(400).json({error:'Transaction and reversal reason are required'});const transaction=(await query(`SELECT at.id FROM account_transactions at JOIN accounts a ON a.id=at.account_id WHERE at.id=$1 AND a.company_id=$2`,[transactionId,req.user.company_id])).rows[0];if(!transaction)return res.status(404).json({error:'Account transaction not found'});const businessId=await generateNextId('FINANCIAL_REVERSAL');const {rows}=await query(`INSERT INTO financial_reversal_requests(business_id,company_id,account_transaction_id,reason,requested_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[businessId,req.user.company_id,transactionId,String(reason).trim(),req.user.id]);await logAction({actorUserId:req.user.id,action:'FINANCIAL_REVERSAL_REQUESTED',entityType:'FINANCIAL_REVERSAL',entityId:businessId,after:{transactionId,reason}});res.status(201).json({reversal:rows[0]});}
async function listReversals(req,res){const {rows}=await query(`SELECT rr.*,at.transaction_type,at.amount,at.reference_type,at.reference_id,a.business_id account_business_id,a.name account_name,u.username requested_username,rv.username reviewed_username FROM financial_reversal_requests rr JOIN account_transactions at ON at.id=rr.account_transaction_id JOIN accounts a ON a.id=at.account_id JOIN users u ON u.id=rr.requested_by LEFT JOIN users rv ON rv.id=rr.reviewed_by WHERE rr.company_id=$1 ORDER BY rr.requested_at DESC`,[req.user.company_id]);res.json({reversals:rows});}
async function reviewReversal(req,res){const {decision,notes}=req.body;if(!['approve','reject'].includes(decision)||!String(notes||'').trim())return res.status(400).json({error:'Decision and review remarks are required'});if(decision==='reject'){const {rows}=await query(`UPDATE financial_reversal_requests SET status='rejected',reviewed_by=$1,reviewed_at=now(),review_notes=$2 WHERE business_id=$3 AND company_id=$4 AND status='pending_approval' RETURNING *`,[req.user.id,notes,req.params.businessId,req.user.company_id]);if(!rows.length)return res.status(409).json({error:'Pending reversal not found'});return res.json({reversal:rows[0]});}const result=await withTransaction(async client=>{const rr=(await client.query(`SELECT rr.*,at.account_id,at.transaction_type,at.amount FROM financial_reversal_requests rr JOIN account_transactions at ON at.id=rr.account_transaction_id WHERE rr.business_id=$1 AND rr.company_id=$2 AND rr.status='pending_approval' FOR UPDATE`,[req.params.businessId,req.user.company_id])).rows[0];if(!rr)throw Object.assign(new Error('Pending reversal not found'),{statusCode:409});const opposite=['WITHDRAWAL','TRANSFER_OUT'].includes(rr.transaction_type)?'DEPOSIT':'WITHDRAWAL';await recordAccountTransaction(client,{accountId:rr.account_id,transactionType:opposite,amount:rr.amount,referenceType:'PAYMENT_REVERSAL',referenceId:rr.business_id,createdBy:req.user.id,notes:`Reversal: ${rr.reason} | ${notes}`});const reversalTx=(await client.query(`SELECT id FROM account_transactions WHERE account_id=$1 AND reference_type='PAYMENT_REVERSAL' AND reference_id=$2 ORDER BY id DESC LIMIT 1`,[rr.account_id,rr.business_id])).rows[0];const voucher=await createFinancialDocument(client,{companyId:req.user.company_id,documentType:opposite==='DEPOSIT'?'MONEY_RECEIPT':'PAYMENT_VOUCHER',accountId:rr.account_id,sourceType:'FINANCIAL_REVERSAL',sourceId:rr.business_id,amount:rr.amount,description:`Approved reversal: ${rr.reason}`,createdBy:req.user.id});return (await client.query(`UPDATE financial_reversal_requests SET status='completed',reviewed_by=$1,reviewed_at=now(),review_notes=$2,reversal_transaction_id=$3,voucher_business_id=$4 WHERE id=$5 RETURNING *`,[req.user.id,notes,reversalTx.id,voucher.business_id,rr.id])).rows[0];});await generateForEntitySafe('PAYMENT_VOUCHER',result.voucher_business_id);await logAction({actorUserId:req.user.id,action:'FINANCIAL_REVERSAL_COMPLETED',entityType:'FINANCIAL_REVERSAL',entityId:result.business_id,after:{notes}});res.json({reversal:result});}

async function createRefund(req,res){const {refundType,accountBusinessId,partyBusinessId,amount,reason,reference}=req.body;if(!['CUSTOMER_REFUND','SUPPLIER_REFUND','EMPLOYEE_REFUND'].includes(refundType)||!accountBusinessId||Number(amount)<=0||!String(reason||'').trim())return res.status(400).json({error:'Refund type, account, positive amount, and reason are required'});const result=await withTransaction(async client=>{const account=(await client.query(`SELECT id FROM accounts WHERE business_id=$1 AND company_id=$2 FOR UPDATE`,[accountBusinessId,req.user.company_id])).rows[0];if(!account)throw Object.assign(new Error('Account not found'),{statusCode:404});let customer=null,vendor=null,employee=null;if(refundType==='CUSTOMER_REFUND')customer=(await client.query(`SELECT id FROM master_customers WHERE business_id=$1 AND company_id=$2`,[partyBusinessId,req.user.company_id])).rows[0];if(refundType==='SUPPLIER_REFUND')vendor=(await client.query(`SELECT id FROM master_vendors WHERE business_id=$1 AND company_id=$2`,[partyBusinessId,req.user.company_id])).rows[0];if(refundType==='EMPLOYEE_REFUND')employee=(await client.query(`SELECT id FROM master_employees WHERE business_id=$1 AND company_id=$2`,[partyBusinessId,req.user.company_id])).rows[0];if(!customer&&!vendor&&!employee)throw Object.assign(new Error('Refund party not found'),{statusCode:404});const businessId=await generateNextId('FINANCIAL_REFUND'),incoming=refundType!=='CUSTOMER_REFUND';await recordAccountTransaction(client,{accountId:account.id,transactionType:incoming?'DEPOSIT':'WITHDRAWAL',amount,referenceType:refundType,referenceId:businessId,createdBy:req.user.id,notes:reason});const voucher=await createFinancialDocument(client,{companyId:req.user.company_id,documentType:incoming?'MONEY_RECEIPT':'PAYMENT_VOUCHER',accountId:account.id,customerId:customer?.id,vendorId:vendor?.id,sourceType:'FINANCIAL_REFUND',sourceId:businessId,amount,description:reason,createdBy:req.user.id});return (await client.query(`INSERT INTO financial_refunds(business_id,company_id,refund_type,account_id,customer_id,vendor_id,employee_id,amount,reason,reference,created_by,voucher_business_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[businessId,req.user.company_id,refundType,account.id,customer?.id||null,vendor?.id||null,employee?.id||null,amount,reason,reference||null,req.user.id,voucher.business_id])).rows[0];});await generateForEntitySafe(result.refund_type==='CUSTOMER_REFUND'?'PAYMENT_VOUCHER':'MONEY_RECEIPT',result.voucher_business_id);res.status(201).json({refund:result});}

async function ledgers(req,res){const {partyType,partyBusinessId}=req.params;let rows=[];if(partyType==='customer')rows=(await query(`SELECT cr.created_at date,cr.source_type type,cr.source_id reference,cr.description,cr.original_amount debit,cr.paid_amount credit,cr.original_amount-cr.paid_amount balance FROM customer_receivables cr JOIN master_customers c ON c.id=cr.customer_id WHERE c.company_id=$1 AND c.business_id=$2 ORDER BY cr.created_at`,[req.user.company_id,partyBusinessId])).rows;else if(partyType==='supplier')rows=(await query(`SELECT po.created_at date,'PURCHASE_ORDER' type,po.business_id reference,po.status description,po.total debit,po.amount_paid credit,po.total-po.amount_paid balance FROM purchase_orders po JOIN master_vendors v ON v.id=po.vendor_id WHERE po.company_id=$1 AND v.business_id=$2 ORDER BY po.created_at`,[req.user.company_id,partyBusinessId])).rows;else if(partyType==='employee')rows=(await query(`SELECT pr.created_at date,'PAYROLL' type,pr.business_id reference,pr.status description,pi.net_pay debit,CASE WHEN pr.status='processed' THEN pi.net_pay ELSE 0 END credit,CASE WHEN pr.status='processed' THEN 0 ELSE pi.net_pay END balance FROM payroll_items pi JOIN payroll_runs pr ON pr.id=pi.payroll_run_id JOIN master_employees e ON e.id=pi.employee_id WHERE pr.company_id=$1 AND e.business_id=$2 ORDER BY pr.created_at`,[req.user.company_id,partyBusinessId])).rows;else return res.status(400).json({error:'Party type must be customer, supplier, or employee'});res.json({partyType,partyBusinessId,entries:rows,closingBalance:rows.reduce((n,x)=>n+Number(x.debit||0)-Number(x.credit||0),0)});}

module.exports={listCostCenters,createCostCenter,requestReversal,listReversals,reviewReversal,createRefund,ledgers};
