import { useState } from 'react';
import { useApi } from '../../lib/useApi';
import { api, downloadApiFile } from '../../lib/apiClient';
import DataTable from '../../components/DataTable';

const money = value => `৳${Number(value || 0).toLocaleString()}`;
const LABELS={summary:'Financial summary',accounts:'Account balances',transactions:'Daily received and account movements',expenses:'Expenses and deductions',bills:'Payables and bills waiting for approval',stockMovements:'Stock movements',receiving:'Products received / GRN',stockReleases:'Products delivered or released',deliveries:'Delivery operations',gatePasses:'Gate and vehicle activity',attendance:'Staff attendance',tasks:'Assigned tasks and task status',machineIncidents:'Machinery incidents',maintenance:'Maintenance activity',requests:'Requests and approvals'};
const nextStage = status => ({prepared:'review',reviewed:'approve',approved:'authorize'})[status];
const title = value => value ? value[0].toUpperCase()+value.slice(1) : '';

export default function ReportWorkflow({date,canCreate,canApprove,availableSections}) {
 const {data,loading,error,reload}=useApi('/daily-financial-reports');
 const options=(availableSections?.length?availableSections:Object.keys(LABELS)).map(key=>[key,LABELS[key]||title(key)]),[sections,setSections]=useState(Object.keys(LABELS)),[selected,setSelected]=useState(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(null);
 const run=async operation=>{setBusy(true);setNotice(null);try{const result=await operation();setNotice({ok:true,text:'Report workflow updated successfully.'});if(result?.report)setSelected(result.report);reload();}catch(e){setNotice({ok:false,text:e.message});}finally{setBusy(false);}};
 const toggle=key=>setSections(current=>current.includes(key)?current.filter(x=>x!==key):[...current,key]);
 const submit=()=>run(()=>api.post('/daily-financial-reports',{date,selectedSections:sections}));
 const sign=(report,stage)=>run(()=>api.post(`/daily-financial-reports/${report.business_id}/sign`,{stage,notes}));
 const actionButtons=report=><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-secondary btn-sm" onClick={()=>setSelected(report)}>Open / review</button><button className="btn btn-secondary btn-sm" onClick={()=>downloadApiFile(`/documents/reports/daily-financial.pdf?date=${report.report_date_text}`,`${report.business_id}.pdf`)}>PDF</button><button className="btn btn-secondary btn-sm" onClick={()=>downloadApiFile(`/documents/reports/daily-financial.csv?date=${report.report_date_text}`,`${report.business_id}.csv`)}>CSV</button>{canApprove&&nextStage(report.status)&&<button className="btn btn-primary btn-sm" disabled={busy} onClick={()=>sign(report,nextStage(report.status))}>{title(nextStage(report.status))}</button>}</div>;
 return <section className="card"><div className="card-header"><div><h2>Report submission and approval</h2><p className="card-subtitle">The reporter selects what goes for approval. Every previous report option is available and selected by default.</p></div>{canCreate&&<button className="btn btn-primary" disabled={busy||!sections.length} onClick={submit}>Submit selected report</button>}</div>
  {canCreate&&<div className="card" style={{marginBottom:16}}><div className="card-header"><strong>Select information for approval</strong><div style={{display:'flex',gap:6}}><button className="btn btn-secondary btn-sm" onClick={()=>setSections(options.map(x=>x[0]))}>Select all</button><button className="btn btn-secondary btn-sm" onClick={()=>setSections([])}>Clear</button></div></div><div style={{display:'flex',gap:18,flexWrap:'wrap'}}>{options.map(([key,label])=><label key={key} style={{display:'flex',alignItems:'center',gap:7}}><input type="checkbox" checked={sections.includes(key)} onChange={()=>toggle(key)}/>{label}</label>)}</div></div>}
  {error&&<div className="error-banner">{error}</div>}{notice&&<div className={notice.ok?'success-banner':'error-banner'}>{notice.text}</div>}
  {loading?<p>Loading…</p>:<DataTable rows={data?.reports||[]} keyField="business_id" emptyMessage="No submitted reports." columns={[{key:'business_id',label:'Report no.'},{key:'report_date_text',label:'Date'},{key:'status',label:'Status'},{key:'prepared_username',label:'Reporter'},{key:'reviewed_username',label:'Reviewed by',render:r=>r.reviewed_username||'—'},{key:'approved_username',label:'Approved by',render:r=>r.approved_username||'—'},{key:'authorized_username',label:'Authorized by',render:r=>r.authorized_username||'—'},{key:'actions',label:'Actions',render:actionButtons}]}/>} 
  {selected&&<div style={{marginTop:20,paddingTop:18,borderTop:'1px solid var(--line)'}}><div className="card-header"><div><h2>{selected.business_id}</h2><p className="card-subtitle">Submitted sections: {(selected.snapshot?.selectedSections||options.map(x=>x[0])).map(x=>LABELS[x]||title(x)).join(', ')}</p></div><button className="btn btn-secondary btn-sm" onClick={()=>setSelected(null)}>Close details</button></div>
   {selected.snapshot?.summary&&<div className="stat-grid">{Object.entries(selected.snapshot.summary).map(([key,value])=><div className="stat-card" key={key}><div className="label">{key.replace(/([A-Z])/g,' $1')}</div><div className="value">{money(value)}</div></div>)}</div>}
   <div className="field"><label>Review / approval remarks</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Enter remarks before signing"/></div>{canApprove&&nextStage(selected.status)&&<button className="btn btn-primary" disabled={busy} onClick={()=>sign(selected,nextStage(selected.status))}>{title(nextStage(selected.status))} report</button>}
   {selected.snapshot?.accounts&&<><h3>Account balances</h3><DataTable rows={selected.snapshot.accounts} columns={[{key:'business_id',label:'Account ID'},{key:'name',label:'Account'},{key:'account_type',label:'Type'},{key:'opening_balance',label:'Opening',render:r=>money(r.opening_balance)},{key:'closing_balance',label:'Closing',render:r=>money(r.closing_balance)}]}/></>}
   {selected.snapshot?.transactions&&<><h3>Daily received and movements</h3><DataTable rows={selected.snapshot.transactions} columns={[{key:'created_at',label:'Time',render:r=>new Date(r.created_at).toLocaleString()},{key:'account_name',label:'Account'},{key:'transaction_type',label:'Movement'},{key:'reference_id',label:'Reference'},{key:'notes',label:'Remarks'},{key:'amount',label:'Amount',render:r=>money(r.amount)}]}/></>}
   {selected.snapshot?.expenses&&<><h3>Expenses and deductions</h3><DataTable rows={selected.snapshot.expenses} columns={[{key:'business_id',label:'Expense'},{key:'category',label:'Category'},{key:'description',label:'Description'},{key:'paid_to',label:'Paid to'},{key:'status',label:'Status'},{key:'amount',label:'Amount',render:r=>money(r.amount)}]}/></>}
   {selected.snapshot?.bills&&<><h3>Payables and approval queue</h3><DataTable rows={selected.snapshot.bills} columns={[{key:'business_id',label:'Bill'},{key:'payee',label:'Payee'},{key:'category',label:'Category'},{key:'status',label:'Status'},{key:'amount',label:'Amount',render:r=>money(r.amount)}]}/></>}
   {(selected.snapshot?.selectedSections||[]).filter(key=>!['summary','accounts','transactions','expenses','bills'].includes(key)).map(key=>{const rows=selected.snapshot[key]||[],keys=[...new Set(rows.flatMap(Object.keys))].slice(0,10);return <div key={key}><h3>{LABELS[key]||title(key)}</h3><DataTable rows={rows} emptyMessage="No records for the selected date." columns={keys.map(k=>({key:k,label:title(k.replaceAll('_',' ')),render:r=>typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}))}/></div>})}
  </div>}
 </section>;
}
