import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useApi } from '../lib/useApi';
import { api, downloadApiFile } from '../lib/apiClient';
import { useAuth } from '../context/AuthContext';
import Pill from '../components/Pill';
import Modal from '../components/Modal';

const fmt=v=>v?new Date(v).toLocaleString(): '—';
export default function BillDetailPage(){
 const {businessId}=useParams(),{data,loading,error,reload}=useApi(`/bills/${businessId}`),{data:accounts}=useApi('/accounts');const {can}=useAuth();
 const [dialog,setDialog]=useState(null),[notes,setNotes]=useState(''),[account,setAccount]=useState(''),[method,setMethod]=useState('bank'),[reference,setReference]=useState(''),[acceptedBy,setAcceptedBy]=useState(''),[busy,setBusy]=useState(false),[actionError,setActionError]=useState('');
 if(loading)return <div className="card">Loading claim…</div>;if(error||!data)return <div className="error-banner">{error||'Claim not found'}</div>;
 const {bill,attachments,history,vouchers,signoffs,reviewer}=data;
 async function act(){setBusy(true);setActionError('');try{if(dialog==='submit')await api.post(`/bills/${businessId}/submit`,{});else if(['approve','reject','return'].includes(dialog))await api.post(`/bills/${businessId}/review`,{decision:dialog,notes});else if(dialog==='pay')await api.post(`/bills/${businessId}/pay`,{accountBusinessId:account,paymentMethod:method,paymentReference:reference,notes});else if(dialog==='accept')await api.post(`/bills/${businessId}/accept`,{acceptedByName:acceptedBy,notes});setDialog(null);setNotes('');await reload()}catch(x){setActionError(x.message)}finally{setBusy(false)}}
 const download=(path,name,preview=false)=>downloadApiFile(path,name,preview).catch(x=>setActionError(x.message));
 return <div><div className="card-header" style={{marginBottom:18}}><div><Link to="/bills">← Bills & claims</Link><h1 className="page-title">{bill.business_id}</h1><p className="card-subtitle">Complete claim, supporting documents, approval trail and vouchers</p></div><Pill status={bill.status}/></div>{actionError&&<div className="error-banner">{actionError}</div>}
 <div className="card" style={{marginBottom:16}}><div className="card-header"><h2>Claim details</h2><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{['draft','returned'].includes(bill.status)&&<button className="btn btn-primary" onClick={()=>setDialog('submit')}>Submit for review</button>}{reviewer&&bill.status==='submitted'&&<><button className="btn btn-primary" onClick={()=>setDialog('approve')}>Approve</button><button className="btn btn-secondary" onClick={()=>setDialog('return')}>Return for correction</button><button className="btn btn-danger" onClick={()=>setDialog('reject')}>Reject</button></>}{bill.status==='approved'&&can('ACCOUNTS_CREATE')&&<button className="btn btn-primary" onClick={()=>setDialog('pay')}>Confirm payment & voucher</button>}{bill.status==='paid'&&<button className="btn btn-primary" onClick={()=>setDialog('accept')}>Confirm payment received</button>}</div></div>
 <div className="form-grid"><Info label="Payee / claimant" value={bill.payee}/><Info label="Category" value={bill.category}/><Info label="Amount" value={`BDT ${Number(bill.amount).toLocaleString('en-BD')}`}/><Info label="Claimant type" value={bill.claimant_type}/><Info label="Bill number" value={bill.bill_number}/><Info label="Bill date" value={bill.bill_date?.slice(0,10)}/><Info label="Submitted by" value={bill.submitter_name||bill.submitter_username}/><Info label="Preferred payment" value={bill.preferred_payment_method}/><Info label="Expense period" value={[bill.expense_start_date?.slice(0,10),bill.expense_end_date?.slice(0,10)].filter(Boolean).join(' to ')}/><Info label="Reviewed by" value={bill.reviewer_username}/><Info label="Payment reference" value={bill.payment_reference}/><Info label="Paid account" value={bill.paid_account_name||bill.paid_account_business_id}/></div><div style={{marginTop:14}}><strong>Description</strong><p>{bill.description||'—'}</p>{bill.review_notes&&<><strong>Review notes</strong><p>{bill.review_notes}</p></>}</div>
 {Array.isArray(bill.expense_breakdown)&&bill.expense_breakdown.length>0&&<div><h3>Expense breakdown</h3>{bill.expense_breakdown.map((x,i)=><div key={i} style={{display:'flex',justifyContent:'space-between',padding:'7px 0',borderBottom:'1px solid var(--border)'}}><span>{x.description}</span><strong>BDT {Number(x.amount||0).toLocaleString('en-BD')}</strong></div>)}</div>}</div>
 <div className="card" style={{marginBottom:16}}><h2>Submitted documents</h2>{attachments.length===0?<p>No documents uploaded.</p>:attachments.map(a=><div key={a.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid var(--border)'}}><div><strong>{a.original_name}</strong><div className="card-subtitle">{a.file_type} · {Math.ceil(a.file_size_bytes/1024)} KB · {fmt(a.created_at)}</div></div><div style={{display:'flex',gap:6}}><button className="btn btn-secondary btn-sm" onClick={()=>download(`/attachments/download/${a.id}`,a.original_name,true)}>Open full document</button><button className="btn btn-secondary btn-sm" onClick={()=>download(`/attachments/download/${a.id}`,a.original_name)}>Download</button></div></div>)}</div>
 <div className="card" style={{marginBottom:16}}><h2>Generated vouchers</h2>{vouchers.length===0?<p>Vouchers appear here after approval and payment.</p>:vouchers.map(v=><div key={v.business_id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid var(--border)'}}><div><strong>{v.business_id}</strong><div className="card-subtitle">{v.document_type.replaceAll('_',' ')} · digitally signed · {fmt(v.created_at)}</div></div><button className="btn btn-primary btn-sm" onClick={()=>download(`/documents/entity/${v.document_type}/${v.business_id}.pdf`,`${v.business_id}.pdf`)}>Download voucher</button></div>)}</div>
 <div className="card"><h2>Audit trail & digital sign-offs</h2>{history.map(h=><div key={h.id} style={{padding:'9px 0',borderBottom:'1px solid var(--border)'}}><strong>{h.action.replaceAll('_',' ')}</strong> · {h.display_name||h.username} · {fmt(h.created_at)}{h.notes&&<div>{h.notes}</div>}</div>)}{signoffs.length>0&&<><h3 style={{marginTop:18}}>Digital signatures</h3>{signoffs.map(s=><div key={s.id}>{s.entity_type} / {s.signoff_role}: <strong>{s.external_name||s.display_name||s.username}</strong> — {fmt(s.signed_at)}</div>)}</>}</div>
 {dialog&&<Modal title={dialog.replaceAll('_',' ')} onClose={()=>setDialog(null)}>{actionError&&<div className="error-banner">{actionError}</div>}{dialog==='pay'&&<><div className="field"><label>Payment account *</label><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Select account</option>{(accounts?.accounts||[]).map(a=><option key={a.id} value={a.business_id}>{a.name} ({a.business_id})</option>)}</select></div><div className="field"><label>Payment method</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="bank">Bank transfer</option><option value="cash">Cash</option><option value="mobile_banking">Mobile banking</option><option value="cheque">Cheque</option></select></div><div className="field"><label>Transaction / cheque reference</label><input value={reference} onChange={e=>setReference(e.target.value)}/></div></>}{dialog==='accept'&&<div className="field"><label>Receiver name</label><input value={acceptedBy} onChange={e=>setAcceptedBy(e.target.value)}/></div>}<div className="field"><label>{['reject','return'].includes(dialog)?'Reason *':'Notes'}</label><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="form-actions"><button className="btn btn-secondary" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy||(['reject','return'].includes(dialog)&&!notes)||(dialog==='pay'&&!account)} className="btn btn-primary" onClick={act}>{busy?'Processing…':'Confirm'}</button></div></Modal>}
 </div>
}
function Info({label,value}){return <div><div className="card-subtitle">{label}</div><strong>{value||'—'}</strong></div>}
