import {useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {useApi} from '../../lib/useApi';
import {api} from '../../lib/apiClient';
import {useAuth} from '../../context/AuthContext';
import DataTable from '../../components/DataTable';
import Modal from '../../components/Modal';
import Pill from '../../components/Pill';

export default function DataCorrectionsPage(){
 const {can}=useAuth(),[params]=useSearchParams(),{data:meta}=useApi('/data-corrections/metadata'),{data,reload}=useApi('/data-corrections');
 const [show,setShow]=useState(false),[selected,setSelected]=useState(null),[form,setForm]=useState({entityType:'CUSTOMER',entityBusinessId:'',operation:'EDIT',reason:'',proposedChanges:{}}),[error,setError]=useState('');
 const {data:detail,reload:reloadDetail}=useApi(selected?`/data-corrections/${selected}`:null),entities=meta?.entities||[],entity=entities.find(x=>x.type===form.entityType);
 useEffect(()=>{const type=params.get('entityType'),id=params.get('entityId');if(type&&id){setForm(f=>({...f,entityType:type,entityBusinessId:id}));setShow(true)}},[params]);
 const setField=(name,value)=>setForm(f=>({...f,proposedChanges:{...f.proposedChanges,[name]:value}}));
 const submit=async e=>{e.preventDefault();try{setError('');await api.post('/data-corrections',form);setShow(false);setForm({entityType:'CUSTOMER',entityBusinessId:'',operation:'EDIT',reason:'',proposedChanges:{}});reload()}catch(x){setError(x.message)}};
 const review=async(decision)=>{const notes=prompt(`${decision} review notes (required)`);if(!notes)return;try{await api.post(`/data-corrections/${selected}/review`,{decision,notes});reload();reloadDetail()}catch(x){alert(x.message)}};
 return <div><div className="card-header"><div><h1 className="page-title">Data correction center</h1><p className="card-subtitle">Controlled editing, soft deletion, restoration, cancellation and reversal requests for every ERP module.</p></div>{can('USER_MANAGEMENT_EDIT')&&<button className="btn btn-primary" onClick={()=>setShow(true)}>New correction request</button>}</div>
 <div className="card"><DataTable rows={data?.requests||[]} emptyMessage="No correction requests." columns={[{key:'business_id',label:'Request'},{key:'entity_type',label:'Module / record type'},{key:'entity_business_id',label:'Record ID'},{key:'operation',label:'Action'},{key:'reason',label:'Reason'},{key:'requested_by_username',label:'Requested by'},{key:'status',label:'Status',render:r=><Pill status={r.status}/>},{key:'actions',label:'',render:r=><button className="btn btn-secondary btn-sm" onClick={()=>setSelected(r.business_id)}>Open / review</button>}]}/></div>
 {show&&<Modal title="Request data correction" onClose={()=>setShow(false)} wide>{error&&<div className="error-banner">{error}</div>}<form onSubmit={submit}><div className="form-grid"><div className="field"><label>Record type *</label><select required value={form.entityType} onChange={e=>setForm({...form,entityType:e.target.value,proposedChanges:{}})}>{entities.map(x=><option key={x.type}>{x.type}</option>)}</select></div><div className="field"><label>Record business ID *</label><input required placeholder="Example: VEN-BD-2026-000001" value={form.entityBusinessId} onChange={e=>setForm({...form,entityBusinessId:e.target.value})}/></div><div className="field"><label>Requested action *</label><select value={form.operation} onChange={e=>setForm({...form,operation:e.target.value})}>{entity?.protected?<><option>REVERSE</option><option>CANCEL</option></>:<><option>EDIT</option>{entity?.softDelete&&<option>DELETE</option>}{entity?.softDelete&&<option>RESTORE</option>}<option>CANCEL</option><option>REVERSE</option></>}</select></div></div>
 {form.operation==='EDIT'&&<div className="card"><h3>Proposed field values</h3><p className="card-subtitle">Enter only fields that need changing. Blank values intentionally clear a field.</p><div className="form-grid">{(entity?.editableFields||[]).map(field=><div className="field" key={field}><label>{field.replaceAll('_',' ')}</label><input value={form.proposedChanges[field]??''} onChange={e=>setField(field,e.target.value)}/></div>)}</div></div>}
 <div className="field"><label>Mandatory correction/deletion reason *</label><textarea required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-primary">Submit for approval</button></div></form></Modal>}
 {selected&&detail?.request&&<Modal title={`${detail.request.business_id} — ${detail.request.operation}`} onClose={()=>setSelected(null)} wide><div className="stat-grid"><div className="stat-card"><div className="label">Record</div><div className="value">{detail.request.entity_business_id}</div><small>{detail.request.entity_type}</small></div><div className="stat-card"><div className="label">Status</div><div className="value">{detail.request.status}</div></div><div className="stat-card"><div className="label">Requested by</div><div className="value">{detail.request.requested_by_username}</div></div></div><div className="card"><p><strong>Reason:</strong> {detail.request.reason}</p><p><strong>Proposed changes:</strong></p><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(detail.request.proposed_changes,null,2)}</pre>{detail.request.review_notes&&<p><strong>Review:</strong> {detail.request.review_notes}</p>}</div>{detail.request.status==='submitted'&&can('USER_MANAGEMENT_APPROVE')&&<div style={{display:'flex',gap:8}}><button className="btn btn-primary" onClick={()=>review('approve')}>Approve and apply safely</button><button className="btn btn-danger" onClick={()=>review('reject')}>Reject</button></div>}<h3>Permanent record audit history</h3><DataTable rows={detail.recordHistory||[]} emptyMessage="No earlier audit entries." columns={[{key:'created_at',label:'Date',render:r=>new Date(r.created_at).toLocaleString()},{key:'action',label:'Action'},{key:'before_data',label:'Previous value',render:r=><code>{JSON.stringify(r.before_data||{})}</code>},{key:'after_data',label:'New value',render:r=><code>{JSON.stringify(r.after_data||{})}</code>}]}/></Modal>}
 </div>;
}
