import {useState} from 'react';import {useApi} from '../../lib/useApi';import {api} from '../../lib/apiClient';import {useAuth} from '../../context/AuthContext';import DataTable from '../../components/DataTable';import Modal from '../../components/Modal';
const emptyForm=()=>({siteId:'',name:'',code:'',description:'',headEmployeeId:'',costCenterId:'',status:'active',operationalSettings:{canReceivePurchases:true,requiresDailyReport:false}});
export default function DepartmentsPage(){
 const {can}=useAuth(),{data,reload}=useApi('/org/departments'),{data:siteData}=useApi('/org/sites'),{data:employeeData}=useApi('/employees'),{data:costData}=useApi('/financial-controls/cost-centers');
 const [show,setShow]=useState(false),[editingId,setEditingId]=useState(null),[selected,setSelected]=useState(null),[form,setForm]=useState(emptyForm()),[staffIds,setStaffIds]=useState([]),[error,setError]=useState('');
 const {data:detail,reload:reloadDetail}=useApi(selected?`/org/departments/${selected}`:null);
 const save=async e=>{e.preventDefault();try{setError('');if(editingId)await api.put(`/org/departments/${editingId}`,form);else await api.post('/org/departments',form);setShow(false);setEditingId(null);if(editingId)reloadDetail();reload()}catch(err){setError(err.message)}};
 const assign=async()=>{try{await api.post(`/org/departments/${selected}/assign-staff`,{employeeBusinessIds:staffIds});setStaffIds([]);reloadDetail();reload()}catch(err){alert(err.message)}};
 const unassign=async employee=>{if(!window.confirm(`Unassign ${employee.full_name} from this department? Historical records and branch location will remain preserved.`))return;try{await api.post(`/org/departments/${selected}/unassign-staff`,{employeeBusinessIds:[employee.business_id]});reloadDetail();reload()}catch(err){alert(err.message)}};
 const edit=()=>{const d=detail.department;setForm({siteId:d.company_site_id||'',name:d.name||'',code:d.code||'',description:d.description||'',headEmployeeId:d.head_employee_id||'',costCenterId:d.cost_center_id||'',status:d.status||'active',operationalSettings:{canReceivePurchases:d.operational_settings?.canReceivePurchases!==false,requiresDailyReport:!!d.operational_settings?.requiresDailyReport}});setEditingId(d.business_id);setError('');setShow(true)};
 const closeForm=()=>{setShow(false);setEditingId(null)};
 const siteLabel=s=>`${String(s.site_type||'location').replaceAll('_',' ')} — ${s.name}${s.address?` — ${s.address}`:''}`;
 const assigned=detail?.department?.staff||[],available=(employeeData?.employees||[]).filter(e=>!assigned.some(a=>a.business_id===e.business_id));
 return <div><div className="card-header"><div><h1 className="page-title">Department management</h1><p className="card-subtitle">Edit departments and control staff assignments at configured locations.</p></div>{can('SETTINGS_CREATE')&&<button className="btn btn-primary" onClick={()=>{setEditingId(null);setForm(emptyForm());setError('');setShow(true)}}>New department</button>}</div>
 <div className="card"><DataTable rows={data?.departments||[]} emptyMessage="No departments configured." columns={[{key:'business_id',label:'Department ID'},{key:'code',label:'Code'},{key:'name',label:'Department'},{key:'site_name',label:'Location',render:r=>r.site_name?`${r.site_name}${r.site_address?` — ${r.site_address}`:''}`:'Not assigned'},{key:'head_name',label:'Head',render:r=>r.head_name||'Not assigned'},{key:'cost_center_name',label:'Cost center',render:r=>r.cost_center_name||'Not assigned'},{key:'staff_count',label:'Staff'},{key:'status',label:'Status'},{key:'actions',label:'',render:r=><button className="btn btn-secondary btn-sm" onClick={()=>setSelected(r.business_id)}>Open</button>}]}/></div>
 {show&&<Modal title={editingId?'Edit department':'Create department'} onClose={closeForm} wide>{error&&<div className="error-banner">{error}</div>}<form onSubmit={save}><div className="form-grid"><div className="field"><label>Configured location *</label><select required value={form.siteId} onChange={e=>setForm({...form,siteId:e.target.value})}><option value="">Select a location</option>{(siteData?.sites||[]).map(s=><option key={s.id} value={s.id}>{siteLabel(s)}</option>)}</select></div><div className="field"><label>Department name *</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Code *</label><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></div><div className="field"><label>Department head</label><select value={form.headEmployeeId} onChange={e=>setForm({...form,headEmployeeId:e.target.value})}><option value="">Not assigned</option>{(employeeData?.employees||[]).map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></div><div className="field"><label>Cost center</label><select value={form.costCenterId} onChange={e=>setForm({...form,costCenterId:e.target.value})}><option value="">Not assigned</option>{(costData?.costCenters||[]).map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></div>{editingId&&<div className="field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></div>}</div><div className="field"><label>Purpose and responsibilities</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div style={{display:'flex',gap:18}}><label><input type="checkbox" checked={form.operationalSettings.canReceivePurchases} onChange={e=>setForm({...form,operationalSettings:{...form.operationalSettings,canReceivePurchases:e.target.checked}})}/> Can receive purchases</label><label><input type="checkbox" checked={form.operationalSettings.requiresDailyReport} onChange={e=>setForm({...form,operationalSettings:{...form.operationalSettings,requiresDailyReport:e.target.checked}})}/> Daily report mandatory</label></div><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={closeForm}>Cancel</button><button className="btn btn-primary">{editingId?'Save changes':'Create department'}</button></div></form></Modal>}
 {selected&&detail?.department&&<Modal title={`${detail.department.code} — ${detail.department.name}`} onClose={()=>setSelected(null)} wide>{can('SETTINGS_CREATE')&&<div className="form-actions" style={{marginTop:0}}><button className="btn btn-primary" onClick={edit}>Edit department</button></div>}<div className="stats-grid"><div className="stat-card"><div className="stat-label">Location</div><div className="stat-value">{detail.department.site_name||'Not assigned'}</div><small>{detail.department.site_address||''}</small></div><div className="stat-card"><div className="stat-label">Head</div><div className="stat-value">{detail.department.head_name||'Not assigned'}</div></div><div className="stat-card"><div className="stat-label">Cost center</div><div className="stat-value">{detail.department.cost_center_name||'Not assigned'}</div></div></div><p>{detail.department.description||'No responsibility description.'}</p><h3>Assigned staff</h3><DataTable rows={assigned} emptyMessage="No staff assigned." columns={[{key:'business_id',label:'Employee'},{key:'full_name',label:'Name'},{key:'designation',label:'Designation'},{key:'status',label:'Status'},{key:'action',label:'',render:r=>can('HR_EDIT')?<button className="btn btn-danger btn-sm" onClick={()=>unassign(r)}>Unassign</button>:null}]}/>{can('HR_EDIT')&&<div className="card"><h3>Assign or transfer staff</h3><p className="card-subtitle">Employees assigned to another department can be transferred here. Existing history is preserved.</p><select multiple size="6" value={staffIds} onChange={e=>setStaffIds([...e.target.selectedOptions].map(x=>x.value))}>{available.map(x=><option key={x.id} value={x.business_id}>{x.full_name} — {x.designation||'Staff'}{x.department_name?` — currently ${x.department_name}`:''}</option>)}</select><button className="btn btn-primary" disabled={!staffIds.length} onClick={assign}>Assign selected staff</button></div>}<h3>Workflow responsibilities</h3><DataTable rows={detail.department.workflows||[]} emptyMessage="No workflow explicitly assigned." columns={[{key:'workflow_key',label:'Workflow'},{key:'display_name',label:'Name'},{key:'enabled',label:'Status',render:r=>r.enabled?'Enabled':'Disabled'}]}/></Modal>}</div>;
}
